# Generated by Django 5.0.4 on 2024-05-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='product_images'),
        ),
    ]
